# -*- coding: utf-8 -*-
"""Plotando_graficos_com_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuCKUpwEfA6j9do1hJuFgW40rjxw7N5w

**Plotando gráfico com Matplotlib**
"""

from random import randrange
import matplotlib.pyplot as plt

notas_matematica = []

for notas in range(8):
  notas_matematica.append(randrange(0,10))

x = list(range(1,9))

y = notas_matematica

plt.plot(x,y,marker='o')

plt.title('Notas de matemática')

plt.xlabel('Provas')
plt.ylabel('Notas')

plt.show()

notas_matematica = ['Matemática',8,7,6,6,7,7,8,10]
notas_portugues = ['Português',9,9,9,8,5,6,8,5]
notas_geografia = ['Geografia',10,10,6,7,7,7,8,7]

notas = [notas_matematica, notas_portugues, notas_geografia]

for materia in notas:
  x = list(range(1,9))
  y = materia[1:]
  plt.plot(x,y,marker='o')
  plt.title(f'notas de {materia[0]}')
  plt.ylabel('Notas')
  plt.xlabel('Provas')
  plt.show()